### ISSUE TITLE
Core functionality of Ataru - how to implement it

### ISSUE THREAD

**Issue by nanoparsec** [CodePadawans/ataru#12]
Today we talked about the general design of Ataru.

Our idea is:

1.The developer has to create a setup module (setup means there have to be all requirements you need to run the application and the application itself) and the markdown files.
2.Ataru extracts the code samples out of markdown files.
It creates a new test class for each markdown file that inherites from Mini::Test and the setup module. It wraps the code samples into test methods and adds them to the related test class.
3.Then all created test methods will be run.
4. There is an output that shows the results.

Question is: Is this a good solution? Or is there something better/easier?

**Comment by kazjote** [comment]
Looks good to me! :+1:

**Comment by code-later** [comment]
Overall that sound reasonable to me, still I have some questions/suggestions:
1. It would be nice if Ataru comes with generator to help you getting started with the setup module.
2. What exactly will be tested in the tests? Do you need to provide assertions in the example itself? Thinking about this, I would not mind doing this… If not, how do determine if a test case was run successfully or not?
3. Ataru should be accessible programmatically (i.e. from a Rake-Task) to make it easy to integrate it into your build process. This is usually not very difficult, just make sure you're not putting too much logic into the executable ;-)

You're doing well young padawans ;-)

**Comment by nanoparsec** [comment]
Thanks Dirk,
1. Okay, that sounds good. We have to figure it out how we can do that.
2. At the moment we grap the code samples and just run them. There are no assertions. It's like a skeleton MiniTest method. Maybe that is not the best way to test the samples but we have no good idea to do it in another way.
3. Good point. Let's find out how we can do that^^.

**Comment by schultyy** [comment]
Concerning the actual test case for a code example, I would say if it runs without throwing an exception it passed.

**Comment by code-later** [comment]
1. The generator would be something for later (a.k.a. rabbit hole). But you should look at the [Thor generators](http://whatisthor.com). Unfortunately, this library is awesome but has terrible documentation…
2. Sound legit for me. Especially for existing projects. But you could recommend to use assertions in the examples. This could even improve the readability of the examples. What do you think @schultyy?
3. You maybe want to look at Thor for the executable as well… If you have any questions, just ask :-)

**Comment by moonglum** [comment]
In my documentations I will often write examples like that:

``` ruby
a = 1 + 2
a #=> 3
```

Maybe you could take that and transform it into a test case like that:

``` ruby
def test_something
  a = 1 + 2
  assert_equal 3, a
end
```

In my experience the "fat arrow" (`=>`) is a common symbol to say: This is the result of this line. And as a reader I would expect that this is **really** the result of that line :wink: So ataru could check if that is really the case.

**Comment by moonglum** [comment]
I think that is the more common way to show an assertion in examples than putting an `assert_x` in there :wink:

**Comment by moonglum** [comment]
Also this would give me the great pleasure to record some screencasts about regular expressions :wink: :wink:

**Comment by code-later** [comment]
@moonglum Like the idea… Anyways, there should be more than just executing.

**Comment by schultyy** [comment]
@railsbros-dirk At first I would start with execution and later on with more advanced topics like assertions you discussed. This also gives @moonglum some time to record screencasts :)

**Comment by code-later** [comment]
@schultyy full ack on that one :-)

**Comment by nanoparsec** [comment]
Okay, i think it woul be better to discuss the different points in different issues:
1. Generator -> https://github.com/CodePadawans/ataru/issues/17
2. Improve tests -> https://github.com/CodePadawans/ataru/issues/19
3. Executable -> https://github.com/CodePadawans/ataru/issues/18

**Comment by nanoparsec** [comment]
So, if ypu agree with our idea of the core functionallity we would implement it in the way it is described above.

**Comment by moonglum** [comment]
I agree with your idea :+1:

**Comment by nanoparsec** [comment]
And the last one: 
Validate Codesample goes to #30
