### ISSUE TITLE
Generator for setup module

### ISSUE THREAD

**Issue by nanoparsec** [CodePadawans/ataru#17]
It would be nice if Ataru comes with generator to help you getting started with the setup module.

**Comment by nanoparsec** [comment]
The generator would be something for later (a.k.a. rabbit hole). But you should look at the Thor generators. Unfortunately, this library is awesome but has terrible documentation…

**Comment by schultyy** [comment]
I found a generator example here: https://github.com/erikhuda/thor/wiki/Generators

**Comment by madziaf** [comment]
`ataru.generate` ataru should have this new method, for the user to easily generate a setup file to pass it together with her md files

**Comment by moonglum** [comment]
So you want to use Thor to generate the setup file. What exactly does the setup file contain? I think I have not yet grasped that.

**Comment by madziaf** [comment]
solved with #55 , ataru setup thor method generates the setup file to be further changed by the user if dependencies for code snippets are needed
