### ISSUE TITLE
Make Ataru accessible programmatically

### ISSUE THREAD

**Issue by nanoparsec** [CodePadawans/ataru#18]
Ataru should be accessible programmatically (i.e. from a Rake-Task) to make it easy to integrate it into your build process. This is usually not very difficult, just make sure you're not putting too much logic into the executable ;-)

**Comment by nanoparsec** [comment]
You maybe want to look at Thor for the executable as well… If you have any questions, just ask :-)

**Comment by moonglum** [comment]
The Thor suggestion is from Mister @railsbros-dirk – right? :laughing: Maybe he can do a screencast about Thor :wink:

**Comment by moonglum** [comment]
Would be useful anyways – because this tool is documented soooo badly. This is why I don't suggest it to people even though it's quite excellent.

**Comment by code-later** [comment]
Definitely! And +1 for the screencast :-)

**Comment by schultyy** [comment]
Yesterday evening I integrated thor in one of my gems: https://github.com/schultyy/orcrist. This is a gem where I do experiments in implementing a programming language.
The special thing here is, that the executable doesn't contain that much code: https://github.com/schultyy/orcrist/blob/master/bin/orcrist

The actual code is in a separate class called `Application` [source](https://github.com/schultyy/orcrist/blob/master/lib/orcrist/cli/application.rb). The advantage of this is, that you can reuse the code for Rake tasks. In a Rake task, you just instantiate an instance of `Application` and call the method which contains the code which calls the `Traverser` and `CodeSamples` class.

**Comment by nanoparsec** [comment]
Solved by pull request #40
