### ISSUE TITLE
Add all dependencies to the Gem spec

### ISSUE THREAD

**Issue by code-later** [CodePadawans/ataru#24]
You're building a Gem and using bundler. Thus you should make sure the Gem defines all it's dependencies to allow bundler to install them.

Dependencies you have are for instance `minitest` and `kramdown`. Currently you need to install them by hand before you could use ataru. This is cumbersome and error-prone. But don't worry, bundler is here to the rescue :-)

For now there are two files of interest for you:
- `Gemfile`
- `ataru.gemspec`

If you open the `Gemfile` you notice the following content:

``` ruby
source "https://rubygems.org"

gemspec
```

The first line just specifies where to look for dependencies. The next line is interesting: `gemspec`. It tells to bundler to look into the `ataru.gemspec` to find the dependencies. Currently there are two dependencies defined in there: `rake` and `bundler`. Both where put there by bundler itself when you generated the gem.

For now you should just add the missing dependencies to `ataru.gemspec`. But don't worry, there is more fun to come with bundler ;-)

**Comment by madziaf** [comment]
done in #32
