### ISSUE TITLE
change `load_file` to a class method

### ISSUE THREAD

**Issue by madziaf** [CodePadawans/ataru#28]
"Adding methods "globally" is very dangerous: Imagine there is another load_file method defined by someone else"

**Comment by schultyy** [comment]
`load_file` shouldn't be a global method.
I suggest that `load_file` should be a class method of `MarkdownLoader`.
Create a class `MarkdownLoader` which has the `load_file` class method so you can later on call load file like this:

``` ruby
MarkdownLoader.load_file(filename)
```

**Comment by madziaf** [comment]
ok!

**Comment by nanoparsec** [comment]
solved by #28
