### ISSUE TITLE
Load Ataru in Target's Gemfile

### ISSUE THREAD

**Issue by emig** [CodePadawans/ataru#46]
It would be nice to being able to add ataru to the project gemfile and
get Ataru load the dependencies of the containing project. 
The Ataru bin executable will be exposed to use in the project

**Comment by moonglum** [comment]
So the workflow would be:
1. Add Ataru to your gem's dependencies.
2. Go to the Ataru folder and run `bundle exec ataru gogo $FILENAMES` (plus some way to say 'use this setup file')

And because we are running in the bundler context, we can `require` all necessary files from the gem.

Correct?

**Comment by emig** [comment]
Yes, that is the idea.
 The user can will require the ataru gem in the Gemfile, and get the functionality. I see this as an enhancement, after having finished #37 and #43.

**Comment by moonglum** [comment]
Ok, cool!

**Comment by emig** [comment]
Closed, this is already done in #37
