### ISSUE TITLE
Check if ataru supports wildcards

### ISSUE THREAD

**Issue by schultyy** [CodePadawans/ataru#51]
Check if ataru can be used with wildcards from commandline like this:

``` bash
$ ataru gogo *.md
```

**Comment by moonglum** [comment]
As the wildcard is a shell feature, this has nothing to do with Ataru. All Ataru has to support is the expanded version of the wildcard aka. multiple filenames which is the case IMHO.

Example:

``` ruby
#!/usr/bin/env ruby

p ARGV
```

Run it in a folder with a lot of thesis files via `./test.rb thesis`:

```
["thesis.aux", "thesis.bbl", "thesis.blg", "thesis.lof", "thesis.log", "thesis.lot", "thesis.out", "thesis.toc"]
```

**Comment by emig** [comment]
prooved by @moonglum. Nice that responsability is already handled by the shell :)
