### ISSUE TITLE
Different Arrows

### ISSUE THREAD

**Issue by moonglum** [CodePadawans/ataru#58]
Currently, only this works:

``` ruby
1 #=> 2
```

This doesn't:

``` ruby
1 # => 2
```

I think both should work, because they are both quite common. To solve this, the RegExp of the scanner has to be adjusted :smile_cat: (This refers to lib/ataru/test_converter.rb, line 14 + 15). If you need help with adjusting it, please ping me :+1: You can again try [Rubular](http://rubular.com/) for this.

**Comment by emig** [comment]
:+1:

**Comment by emig** [comment]
closed by eae8e0533825041a2af50e70666dae9368d13bc7
