### ISSUE TITLE
Assertions do not run.

### ISSUE THREAD

**Issue by moonglum** [CodePadawans/ataru#59]
There is a problem with the convertion of `#=>` to assertions. To demonstrate the problem, run ataru against [this Markdown file](https://gist.github.com/moonglum/82d987893b57b1898385). It will not find any assertions and it will therefore not find the 'bug' in the Markdown file.

To narrow down the problem, print the code that should be evaluated. To do that, go to the file `lib/ataru/code_sample.rb` and `p self.code`. You will see that it prints the following:

``` ruby
1 #=> 2assert_equal 2, 1 now
```

As you can see, this is not what you want to be happening, because now the assertion is in the comment. So all Ruby can see is `1`, which of course is not an assertion.
## Hint

The error is somewhere in `lib/ataru/application.rb`. You can print out the values of `status`, `assertion` and `code_sample.code` – and then see what `code_sample` is after the `if status == :ok ... end` block :smile: You will see that there's something going wrong here.

I'm available for more hints.

PS: I have repaired it locally, but I run into another error (`assert_equal` is not defined). But I will investigate this further later :wink:

**Comment by dariocravero** [comment]
:+1: :) keep the good work up! This looks very promising! :clap: :heart:

BTW, faced this issue just now. At first I was scratching my head as to how to test anything and then found the example gem showing that `#=>` would assert something and right after I found this open issue.

**Comment by madziaf** [comment]
@dariocravero thanks for looking into ataru :) 
I think we just solved that issue. We welcome more issues, if you happen to find more bugs:)

**Comment by dariocravero** [comment]
Brilliant! :) Thanks, will give it a go now again ;)

**Comment by madziaf** [comment]
solved with #64
