### ISSUE TITLE
change gogo method

### ISSUE THREAD

**Issue by madziaf** [CodePadawans/ataru#67]
At the moment user has to type all .md files that she wants to have checked with ataru.
'gogo' can be enhanced so it 
- either checks and loads all the .md files of the project (that would be default)
- or takes specific .md files (as it does currently).
  It would work similarily when user wants to add ataru into the Travis run:
- default would load all .md files
- if user wants to manually specify which files should be checked, she could write .ataru.rc file and list there all .md files. .ataru.rc file would be loaded for the Travis run.

**Comment by moonglum** [comment]
What do you think of the following:
- `ataru gogo` takes all Markdown files or all markdown files as specified by `.ataru.rc`
- `ataru go test.md` takes a number of Markdown file names

**Comment by code-later** [comment]
Why do you want to separate those commands? I would expect something like this:
- `ataru go` using all Markdown files or all as specified by `ataru.rc`
- `ataru go test.md` just the defined file

**Comment by emig** [comment]
:+1: on this with @railsbros-dirk

**Comment by moonglum** [comment]
Ok, I should have explained that :laughing: So in my opinion 'search for all Markdown files in an entire tree' is not something I would expect as a default behavior (_This is purely philosophical and personal opinion_). I therefore would suggest having a separate command for that behavior.

**Comment by code-later** [comment]
OK then, let's have a philosophical discussion :-)

Why is not expected behavior? Ataru is build for finding and checking Markdown files in the current project / directory. Using a different command seems less intuitive to me.

And by the way, most of the tools I use do this (not looking at just one file per default): `ag`, `rspec`, `vim`…

**Comment by moonglum** [comment]
I agree with your explanation. Let's do it with a recursive search :wink: I already gave @madziaf some hints on how to do it :smile: 

_PS: I agree with `rspec`. I don't agree with vim. vim opens an empty buffer when you start it without an argument. Otherwise it behaves exactly the way that 'vim [filelist]'  does by setting the root accordingly._

**Comment by emig** [comment]
Contributing to endless scholastic chat:

A separate command should indicate there is a very different responsibility.
In this case I don't see an essential change of behaviour, but just a
different input being passed.

To handle concerns expressed by @moonglum, an option could be to pass a flag
--all(-a). 

`ataru gogo -a` to let ataru find all .md files.

**Comment by moonglum** [comment]
@emig An `-a` flag would let me feel a little bit more comfy indeed :smile: 

One big difference to `rspec` is also that `rspec` is not searching everywhere – but only at some paths that come from conventions (The `spec` folder blabla).

**Comment by schultyy** [comment]
Concerning `rspec` and conventions:
For new projects ataru could offer something similar, a predefined folder (structure) where project documentation lives.

**Comment by code-later** [comment]
OK, `-a` it is? I'm fine with that :-)

@moonglum I don't agree that `rspec` is a **big difference**. The `spec` folder is just the only one interesting for `rspec`. For `ataru` the entire directory is of interest ;-) And regarding your Vim comment: Starting Vim without arguments already sets 'pwd`to the the current directory. Even`path`includes this. But`vim` maybe indeed be not the best example :tongue:

**Comment by moonglum** [comment]
Ok, then we agree on that!

@railsbros-dirk Hehe, ok :wink:

**Comment by emig** [comment]
Yea,  this way we can still throw error when ataru is not passed any argument or flag or configuration file, and give no option to the user than to read the nice Thor's usage info :)

**Comment by madziaf** [comment]
hi ho!
tut mir leid, but there will be no flags.
Here's the output when trying to implement thor option for method `go`:

```
➜  ataru git:(50-travis) ✗ bin/ataru go  -a
{"all_md_files"=>true}

invalid option: -a

minitest options:
    -h, --help                       Display this help.
    -s, --seed SEED                  Sets random seed
    -v, --verbose                    Verbose. Show progress processing files.
    -n, --name PATTERN               Filter run on /pattern/ or string.

Known extensions: pride
    -p, --pride                      Pride. Show your testing pride!
```

**Comment by madziaf** [comment]
It will be possible to pass filenames or ataru will look for all the .md files in the project.

**Comment by emig** [comment]
It seems minitest gets confused with the options method from Thor.
I suggested Magda to do it without flag until we check the error.

**Comment by moonglum** [comment]
:+1:

**Comment by madziaf** [comment]
Erik says with the flag with thor we could try to write the flag before the method name, like:
`bundle exec ataru -a check`

**Comment by madziaf** [comment]
done in #69
