### ISSUE TITLE
Introduce Travis

### ISSUE THREAD

**Issue by moonglum** [CodePadawans/ataru#8]
Travis is a great way to make sure that all your tests pass. It works like that:
- You commit something in Git and then push it to Github
- Travis will see that and start running your test suite on their computers
- Travis will see if the tests passed or did not pass – if it doesn't pass you will get an email

This helps you to maintain what we call a 'green build'. That means that all your tests always pass on your master branch.

If you like that, then the following steps need to be done:
1. Find a single command in the terminal to run all tests
2. Sign up with travis
3. Activate webhooks
4. Set up a `.travis.yml` file in your project which tells travis how to run the tests (from step 1 – this is the `script` part) and that it is a Ruby project.
5. Push :+1: Travis should give you feedback now!
6. Be amazed.

![Be Amazed](https://cloud.githubusercontent.com/assets/95788/3826536/2b14a604-1d63-11e4-965e-133e1255c228.gif)

This is described in detail [here](http://docs.travis-ci.com/user/getting-started). If you want more hints at one of the steps, just ask :smile:

**Comment by nanoparsec** [comment]
It worked <3

**Comment by nanoparsec** [comment]
Solved in Pull Requests #9 & #10

**Comment by moonglum** [comment]
Great work! :smile_cat: I thought today would be more like that:

![image](https://cloud.githubusercontent.com/assets/95788/3859308/38f4ac8c-1f17-11e4-9238-609e35dc04aa.gif)

But you did it anyways :dancer:
